# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-XMLRPC
version:      0.05
version_from: XMLRPC.pm
installdirs:  site
requires:
    Catalyst:                      5.01
    RPC::XML:                      1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
