abstract: Dispatch XMLRPC methods with Catalyst
author: Sebastian Riedel, C<sri@oook.de>
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Catalyst-Plugin-XMLRPC
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.64
  RPC::XML: 0
version: 1.0
